spring.application.name=price-comparator

spring.datasource.url=jdbc:postgresql://localhost:5432/price_comparator
spring.datasource.username=developer
spring.datasource.password=dev_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true