CREATE TABLE product
(
    id       VARCHAR(50) PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    brand    VARCHAR(255) NOT NULL,
    category VARCHAR(255),
    quantity DOUBLE PRECISION,
    unit     VARCHAR(50)
);

CREATE TABLE store
(
    id   SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE discount
(
    id         SERIAL PRIMARY KEY,
    product_id VARCHAR(50) NOT NULL REFERENCES product (id),
    store_id   INTEGER     NOT NULL REFERENCES store (id),
    from_date  DATE        NOT NULL,
    to_date    DATE        NOT NULL,
    percentage INTEGER     NOT NULL,
    CONSTRAINT uq_discount UNIQUE (product_id, store_id, from_date, to_date)
);

DROP TABLE IF EXISTS price_snapshot CASCADE;

CREATE TABLE price_snapshot
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(50)    NOT NULL REFERENCES product (id),
    store_id   INTEGER        NOT NULL REFERENCES store (id),
    date       DATE           NOT NULL,
    price      NUMERIC(10, 2) NOT NULL,
    currency   VARCHAR(10)    NOT NULL,
    CONSTRAINT uq_price_snapshot UNIQUE (product_id, store_id, date)
);